#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=16:00:00
#PBS -N bedpostx
#PBS -l vmem=16gb
#PBS -V

export SINGULARITYENV_LD_LIBRARY_PATH=$CUDA91PATH/lib64

dwi=`jq -r '.dwi' config.json`;
bvecs=`jq -r '.bvecs' config.json`;
bvals=`jq -r '.bvals' config.json`;
mask=`jq -r '.mask' config.json`;

mkdir input_folder
cp $mask input_folder/nodif_brain_mask.nii.gz
cp $dwi input_folder/data.nii.gz
cp $bvals input_folder/bvals
cp $bvecs input_folder/bvecs

nf=`jq -r '.nf' config.json`;
fudge=`jq -r '.fudge' config.json`;
bi=`jq -r '.bi' config.json`;

time singularity exec -e --nv docker://brainlife/fsl:6.0.1 bedpostx_gpu input_folder --nf=$nf --fudge=$fudge  --bi=$bi





